Ais\MatakuliahBundle\Entity\Matakuliah:
 type: entity
 table: matakuliah
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  kode:
   type: string
   length: 10
   unique: true
  nama:
   type: string
   length: 100
  nama_singkat:
   type: string
   length: 30
   nullable: true
  prodi_id:
   type: integer
   nullable: true
  is_active:
   type: boolean
   nullable: true
  is_delete:
   type: boolean
   nullable: true
