<?php

namespace Ais\MatakuliahBundle\Repository;

/**
 * MatakuliahRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatakuliahRepository extends \Doctrine\ORM\EntityRepository
{
}
